### ISSUE TITLE
Going to be away for a while.

### ISSUE THREAD

**Issue by ghost** [OpenTechEngine/Discussions#19]
Hi guys, I'm in the process of moving to another country and won't be taking my desktop with me, so I'll be away from the project for a while until I have everything settled and built a new system. I don't want to release the assets I have so far as I want the release to be a surprise. I'm not sure how long I will be away from the project, so if I'm scarce it's due to the move.

**Comment by BielBdeLuna** [comment]
np

**Comment by Anthony-Gaudino** [comment]
If you don't mind my curiosity, where are you moving to?

I'm also interested in moving to another country in the future  ;)

Good luck for you!

**Comment by ghost** [comment]
@Anthony-Gaudino Japan

**Comment by Anthony-Gaudino** [comment]
@Yetta1  Dang it, how I envy you :rage:
Just kidding, LOL

I tried to get a scholarship to study in Japan, but I failed.
Now I will try for another country XD

I lived in South Korea for 6 months some years ago, it was great, everything was so much better than the hellhole I live (Brazil).
By the way, to anyone that is reading this: **DON'T COME TO 2016 OLYMPICS**.

I don't know why you're going to Japan, but I hope you enjoy it.
You may only dislike it if you are from USA or another occidental developed country. I remember that Americans working in Korea didn't like living there so much, they missed their own country.
For me everything in Korea was great, only some traditional food was bad because they put too much pepper on it, so if you don't like sushi you may have problems too.

**Comment by ghost** [comment]
@Anthony-Gaudino I'm South African and I completely understand your situation in Brazil, we are similar in that regard, except we don't have the world's most gorgeous women unlike Brazil. I was thinking of moving to Brazil some time ago, but decided against it as I'm already worn out from the crime in my own country, no point going to another one with gangs that have heavier weapons.

I was thinking about South Korea, but feel that I won't fit into that culture too well, Japan seems a bit more open towards people with different tastes and Japan has some really good hardware at good prices. Luckily I love sushi and don't mind eating weird things, already had my rounds with obscure African foods.

You should look into jobs in Japan, There is a ton of jobs open for people that speak English at some big corporations. Strangely enough I got one for Afrikaans translation, kind of weird considering my culture is undergoing a cultural genocide in this country.

**Comment by Anthony-Gaudino** [comment]
@Yetta1 you did great by not coming to Brazil.
The idea that Brazil is full of beautiful women is wrong, actually most are ugly, in some very special places you can find more beautiful women, like in some beaches in Rio.
What is true is that Brazilian women want to be beautiful, usually rich people are more beautiful because they can spend a lot in plastic surgery and cosmetics, so when you see a gorgeous women she could have made surgery or be hiding under cosmetics. Many women also do exercises to become more athletic and beautiful. Of course there are women that are just naturally beautiful like you find anywhere in the world.

Brazil has a lot of violence, corruption and nothing works well, economy is going very bad right now too.

Korea also has great hardware at good prices, I don't know how it compares to Japan though.
I bought a PC in Korea and it was super cheap compared to Brazil.

Native English speakers have better opportunities to live in other countries, they can work as English teachers for example. My native language, Brazilian Portuguese, is not very useful.

Thanks, I will search, but I believe most jobs will require Japanese language and/or that you already live in Japan.

**Comment by BielBdeLuna** [comment]
Monolingualism isn't great either when in comes to communication, so knowing Brazilian Portuguese and English is great!
